export const STRINGS = {
  appTitle: 'GenAI Sustainability Advisor',
  inputMaterial: 'Input Material',
  uploadImage: 'Analyze Compatibility',
  placeholderDescription: '',
  sustainabilityScore: 'Sustainability Score',
  ecoFriendlyAlternative: 'Sustainable Alternative',
  disposalMethod: 'Disposal Method',
  detailedInsights: 'Detailed Sustainability Insights',
  exportReport: 'Export Report',
  permissionError: 'Sorry, we need media library permissions to make this work!',
  finalProductCompatibility: 'Final Product',
  rawMaterial: 'Raw Material',
  finalProductPlaceholder: 'e.g., “Table”, “Sportswear”, “Electronic case”',
  inputPlaceholder: 'e.g., “Apple”, “Hydrochloride”, “Sodium bicarbonate”',
  finalProductButton: 'Check Material Compatibility',
  description: 'Description',
  alertNoImage: 'Please select an image first.',
  alertNoInput: 'Please enter a compatibility input first.',
  genericError: 'Something went wrong',
};
