import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '../constants/colors';

const { width, height } = Dimensions.get('window');
const inputButtonHeight = height * 0.045; // 25% smaller height

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 15,
    marginTop: 0,
    marginBottom: 0,
    backgroundColor: COLORS.background,
  },
  title: {
    fontSize: width * 0.035,
    fontWeight: 'bold',
    marginBottom: 10,
    color: COLORS.primary,
    textAlign: 'center',
    marginTop: 10
  },
  row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  inputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  column: {
    flex: 1,
    paddingHorizontal: 8,
  },
  InsightsMainContainer: {
    flex: 3,
    padding: 16,
    marginRight: 8,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 6,
    width: '100%',
    marginTop: 10
  },
  InputContainer: {
    padding: 16,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 6,
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 10,
  },
  sectionHeader: {
    fontSize: width * 0.03,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 12,
  },
  compatibilityBlock: {
    flex: 1,
    marginLeft: 10,
  },
  imageBlock: {
    flex: 1,
  },
  inputBlock: {
    width: '100%',
  },
  imageCard: {
    width: '100%',
    height: height * 0.2,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: COLORS.border,
    backgroundColor: COLORS.cardBackground,
    marginBottom: 10,
  },
  placeholderImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  uploadButton: {
    backgroundColor: COLORS.button,
    height: inputButtonHeight,
    justifyContent: 'center',
    borderRadius: 10,
    width: '100%',
    marginTop: 5,
    marginBottom: 12,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
  },
  compatibilityButton: {
    backgroundColor: COLORS.button,
    height: inputButtonHeight,
    justifyContent: 'center',
    borderRadius: 10,
    width: '100%',
    marginTop: 5,
    marginBottom: 12,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
    bottom: 0,
  },
  uploadText: {
    color: COLORS.buttonText,
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 0.5,
    fontSize: 18,
  },
  compatibilityLabel: {
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 6,
    marginLeft: 6,
    marginTop: 6,
    color: COLORS.textDark,
  },
  compatibilityInput: {
    borderWidth: 1,
    borderColor: COLORS.secondary,
    borderRadius: 10,
    backgroundColor: '#f0faf7',
    paddingHorizontal: 12,
    height: inputButtonHeight,
    marginBottom: 16,
    fontSize: 14,
    color: COLORS.textDark,
  },
  descriptionLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
    marginLeft: 6,
    color: COLORS.textDark,
  },
  descriptionDisplay: {
    height: height * 0.3,
    padding: 6,
    textAlignVertical: 'top',
    fontSize: 14,
    color: COLORS.textDark,
  },
  descriptionDisplayView: {
    height: height * 0.2,
    fontSize: 16,
    borderWidth: 1,
    borderColor: COLORS.secondary,
    borderRadius: 10,
    backgroundColor: '#e0f2f1',
    marginBottom: 10,
  },
  sustainabilitySection: {
    // borderBottomWidth: 2,
    // borderColor: COLORS.border,
    paddingBottom: 10,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
  },
  scoreCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: COLORS.accent,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
    marginRight: 20,
  },
  score: {
    fontSize: 32,
    fontWeight: 'bold',
    color: COLORS.buttonText,
  },
  cardRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingTop: 20,
  },
  scoreCard: {
    flex: 1,
    minHeight: 100,
    borderWidth: 1,
    borderColor: COLORS.accent,
    borderRadius: 10,
    padding: 12,
    backgroundColor: COLORS.cardBackground,
  },
  cardTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: COLORS.textDark,
  },
  cardSubtitle: {
    fontSize: 14,
    color: COLORS.textDark,
    marginTop: 6,
  },
  insightsContainer: {
    marginBottom: 16,
    flex: 1,
  },
  insightsSubtitle: {
    fontSize: 16,
    color: COLORS.textDark,
    marginTop: 6,
  },
  exportButton: {
    // alignSelf: 'flex-start',
    // paddingVertical: 12,
    // paddingHorizontal: 22,
    // borderRadius: 10,
    // backgroundColor: COLORS.button,
    // shadowColor: COLORS.primary,
    // shadowOpacity: 0.2,
    // shadowRadius: 6,
    // elevation: 5,
    flex: 1, 
    alignItems: 'flex-end',
    marginTop: -15
  },
  exportText: {
    color: COLORS.buttonText,
    fontWeight: '600',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: COLORS.cardBackground,
    padding: 24,
    borderRadius: 16,
    width: '70%',
    borderColor: COLORS.accent,
    borderWidth: 1,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    color: COLORS.primary,
    marginBottom: 16,
  },
  modalOption: {
    fontSize: 16,
    paddingVertical: 12,
    textAlign: 'center',
    color: COLORS.textDark,
  },
  modalCancel: {
    fontSize: 16,
    color: COLORS.primary,
    textAlign: 'center',
    padding: 12,
    fontWeight: 'bold',
  },
  inputMaterialValue: {
    fontSize: width * 0.025,
    color: COLORS.primary,
    marginBottom: 12,
    textAlignVertical: 'bottom',
    marginLeft: 4
  },
  speakerIcon: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 10,
  },
  leafAnimationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -90 }, { translateY: -10 }], // Adjusted to better center the leaves
  },
  animatedLeaf: {
    margin: 5,
  },
  loadingOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Transparent overlay
  },
  deleteIcon: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 10,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 4,
  },
  scoreBarContainer: {
    flex: 1,
    marginRight: 20,
    justifyContent: 'center',
  },
  
  scoreBarBackground: {
    width: '100%',
    height: 20,
    backgroundColor: '#e0e0e0',
    borderRadius: 10,
    overflow: 'hidden',
  },
  
  scoreBarFill: {
    height: '100%',
    backgroundColor: '#4caf50', // default green, can enhance with gradient or dynamic color
  },
  scoreLabel: {
    marginTop: 6,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  headerIcon: {
    marginRight: 8, 
    marginTop: -10
  },
  sustainabilityIcon: {
    marginRight: 8,
    alignSelf: 'center',
  },
  titleIcon: {
    marginRight: 4, 
    // marginTop: -5
  },
});
